version: "3"
services:
  psql:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: order_microservice
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
  web:
    image: waghih/setel-assignment-web:latest
    resources:
      limits:
        cpus: '0.001'
        memory: 50M
      reservations:
        cpus: '0.0001'
        memory: 20M
    ports:
      - 5000:5000
  order:
    image: waghih/setel-assignment-order:latest
    memory: 512
    ports:
      - 4200:4200
    environment:
      DB_HOST: psql
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASS: 
      DB_DIALECT: postgres
      PAYMENT_HOST: payment
      ORDER_HOST: order
    links:
      - psql
  payment:
    image: waghih/setel-assignment-payment:latest
    memory: 512
    ports:
      - 4001:4001
    environment:
      PAYMENT_HOST: payment
      ORDER_HOST: order
